// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0tnHbjE6vwjV0AcAvkfj4BGz5E67VOKY',
    appId: '1:902995726107:web:79dcfdca8d5ad366694dbe',
    messagingSenderId: '902995726107',
    projectId: 'testproj-8073c',
    authDomain: 'testproj-8073c.firebaseapp.com',
    storageBucket: 'testproj-8073c.appspot.com',
    measurementId: 'G-JDLH08R4F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnWZ1mEeEif75R6begLsFC_e3cuuy_JVM',
    appId: '1:902995726107:android:185e320952af141d694dbe',
    messagingSenderId: '902995726107',
    projectId: 'testproj-8073c',
    storageBucket: 'testproj-8073c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6oa8kVhTKcSHdC80BXOu1_SAlzcjtwr8',
    appId: '1:902995726107:ios:f3d44e1a4313cb84694dbe',
    messagingSenderId: '902995726107',
    projectId: 'testproj-8073c',
    storageBucket: 'testproj-8073c.appspot.com',
    iosClientId: '902995726107-rg3vkdmurplv3kjbbkabg4naevghicpr.apps.googleusercontent.com',
    iosBundleId: 'watanabekizuna.testproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6oa8kVhTKcSHdC80BXOu1_SAlzcjtwr8',
    appId: '1:902995726107:ios:f3d44e1a4313cb84694dbe',
    messagingSenderId: '902995726107',
    projectId: 'testproj-8073c',
    storageBucket: 'testproj-8073c.appspot.com',
    iosClientId: '902995726107-rg3vkdmurplv3kjbbkabg4naevghicpr.apps.googleusercontent.com',
    iosBundleId: 'watanabekizuna.testproj',
  );
}
